# Generated by Django 3.0.7 on 2020-06-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='album',
        ),
    ]
